var secondsPerMin = 60;
var minsPerHour = 60;
var hoursPerDay = 24;
var daysPerWeek = 7;
var weeksPerYear = 52;
var secondsPerDay = secondsPerMin * minsPerHour * hoursPerDay;
document.write('There are ' + secondsPerDay + ' seconds in a day');
var yearsAlive = 3;
var secondsPerYear = secondsPerDay * daysPerWeek * weeksPerYear;
secondsAlive = secondsPerYear * yearsAlive;
document.write("I've been alive for more than " + secondsAlive + " seconds!");